# Configure main menu and social menu
[[main]]
identifier = "categories"
name = "Categories"
url = "/categories"
[main.params]
icon = "categories"
[[main]]
identifier = "tags"
name = "Tags"
url = "/tags"
[main.params]
icon = "tag"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/RikaCelery"

[social.params]
icon = "brand-github"
newtab = true

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/Celery1806"

[social.params]
icon = "brand-twitter"
newtab = true
